/**
 * AI_MODE=mock: a deterministic, evidence-aware pseudo-analysis so local work
 * and end-to-end tests run token-free. Scores derive from what the package
 * actually contains and every reason cites REAL package ids, so the whole
 * validation path (zod + reference check + composite) runs exactly as live.
 *
 * Stored with is_mock=true and never reused for a real request.
 */
import type { EvidenceItem } from "./evidence";
import { FIT_DIMENSIONS, type FitDimension, type ModelFitOutput } from "./fit-schema";

export function mockFitOutput(input: { funderName: string; items: ReadonlyArray<EvidenceItem> }): ModelFitOutput {
  const items = input.items;
  const ids = new Set(items.map((i) => i.id));
  const byPrefix = (p: string) => items.filter((i) => i.id.startsWith(p)).map((i) => i.id);
  const first = items[0]?.id ?? "identity";
  const pick = (...preferred: string[]): string[] => {
    for (const p of preferred) if (ids.has(p)) return [p];
    for (const p of preferred) {
      const hits = byPrefix(p);
      if (hits.length > 0) return [hits[0]];
    }
    return [first];
  };

  const text = (id: string) => items.find((i) => i.id === id)?.text ?? "";
  const applicantState = /state ([A-Z]{2})\b/.exec(text("applicant_place"))?.[1] ?? null;
  const geography = text("geography");
  const sameState = applicantState ? geography.includes(`${applicantState}:`) : false;
  const posture = byPrefix("posture_").map(text).join(" ");
  const open = /Accepts applications/.test(posture);
  const preselected = /preselected/i.test(posture);
  const hasGrants = ids.has("grant_stats");
  const grantCount = byPrefix("grant_").filter((id) => /^grant_\d+$/.test(id)).length;
  const hasFinancials = byPrefix("financials").length > 0;
  const hasProfile = ids.has("applicant_profile");

  const dim = (score: number, statement: string, evidenceIds: string[], confidence: "low" | "medium" | "high" = "medium") => ({
    score,
    statement,
    evidenceIds,
    confidence,
  });

  const dimensions: Record<FitDimension, ReturnType<typeof dim>> = {
    mission_alignment: dim(
      hasProfile && grantCount > 0 ? 62 : 45,
      hasProfile
        ? "Mock: grant purposes on file were compared with the applicant's stated program areas."
        : "Mock: the applicant profile is empty, so mission overlap cannot be judged.",
      pick("applicant_profile", "grant_1", "identity"),
      hasProfile ? "medium" : "low",
    ),
    geography: dim(
      sameState ? 80 : applicantState ? 35 : 50,
      sameState
        ? "Mock: this funder's grants include recipients in the applicant's state."
        : applicantState
          ? "Mock: no grants to the applicant's state appear in the package."
          : "Mock: the applicant has no state on file, so geography is unknown.",
      pick("geography", "identity"),
      applicantState ? "medium" : "low",
    ),
    grant_size_fit: dim(
      grantCount > 0 ? 58 : 40,
      grantCount > 0 ? "Mock: judged from the largest grants listed in the package." : "Mock: no grant rows on file to size an ask.",
      pick("grant_1", "grant_stats", "identity"),
      "low",
    ),
    applicant_eligibility: dim(
      55,
      "Mock: no stated restriction in the package rules the applicant out.",
      pick("posture_1", "applicant_profile", "identity"),
      "low",
    ),
    recency: dim(
      hasGrants ? 70 : 30,
      hasGrants ? "Mock: a documented grant history is on file." : "Mock: no grant history on file.",
      pick("grant_stats", "financials", "identity"),
      hasGrants ? "high" : "low",
    ),
    capacity: dim(
      hasFinancials ? 65 : 40,
      hasFinancials ? "Mock: latest filing shows distributions and assets." : "Mock: no financials on file.",
      pick("financials", "identity"),
      hasFinancials ? "medium" : "low",
    ),
    openness: dim(
      open ? 85 : preselected ? 25 : 50,
      open
        ? "Mock: the latest 990-PF states that applications are accepted."
        : preselected
          ? "Mock: the latest 990-PF states the funder gives to preselected organizations only."
          : "Mock: the filings carry no application statement. That is an absence, not a closed door.",
      pick("posture_1", "identity"),
      open || preselected ? "high" : "medium",
    ),
  };

  return {
    dimensions,
    summary:
      `Mock analysis of ${input.funderName}: ` +
      `${sameState ? "gives in the applicant's state" : "no in-state grants found"}, ` +
      `${open ? "accepts applications" : preselected ? "funds preselected organizations only" : "application posture not stated in filings"}, ` +
      `${hasGrants ? "has a grant history on file" : "no grant history on file"}. ` +
      "Generated by AI_MODE=mock for development and testing; it is not a real analysis.",
    topReasons: [
      {
        statement: hasGrants ? "Mock: documented grantmaking on file." : "Mock: the funder exists in public filings.",
        evidenceIds: pick("grant_stats", "identity"),
        confidence: "medium",
      },
    ],
    concerns: open
      ? []
      : [
          {
            statement: preselected
              ? "Mock: the funder says it gives to preselected organizations; an introduction may be needed."
              : "Mock: no application process is stated; cultivation may be needed.",
            evidenceIds: pick("posture_1", "identity"),
            confidence: "medium",
          },
        ],
    suggestedAsk:
      grantCount > 0
        ? {
            min: 10_000,
            max: 50_000,
            confidence: "low",
            rationale: "Mock range taken from the presence of grant rows, not their amounts.",
            evidenceIds: pick("grant_1", "grant_stats"),
          }
        : null,
    suggestedNextStep: {
      action: open ? "Read the how-to-apply text and note the deadline." : "Look for a warm introduction before writing.",
      rationale: "Mock next step keyed to the application posture.",
    },
    approachAngle: "Lead with: the work you already do in the places this funder gives. Avoid leading with: a general ask.",
  };
}

export const MOCK_FIT_DIMENSIONS = FIT_DIMENSIONS;
